# Generated by Django 3.0.5 on 2020-04-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Person1',
        ),
    ]
